<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="23" started-at="2022-10-17T10:05:33Z" finished-at="2022-10-17T10:05:33Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="23" started-at="2022-10-17T10:05:33Z" finished-at="2022-10-17T10:05:33Z">
      <class name="basicsOfTestNG.firstTestNGProgram">
        <test-method status="PASS" signature="tc2()[pri:1, instance:basicsOfTestNG.firstTestNGProgram@6574b225]" name="tc2" duration-ms="5" started-at="2022-10-17T17:05:33Z" finished-at="2022-10-17T17:05:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc2 -->
        <test-method status="FAIL" signature="tc1()[pri:2, instance:basicsOfTestNG.firstTestNGProgram@6574b225]" name="tc1" duration-ms="2" started-at="2022-10-17T17:05:33Z" finished-at="2022-10-17T17:05:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [14] but found [12]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [14] but found [12]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:388)
	at org.testng.Assert.assertEquals(Assert.java:398)
	at basicsOfTestNG.firstTestNGProgram.tc1(firstTestNGProgram.java:9)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc1 -->
        <test-method status="PASS" signature="tc3()[pri:3, instance:basicsOfTestNG.firstTestNGProgram@6574b225]" name="tc3" duration-ms="1" started-at="2022-10-17T17:05:33Z" finished-at="2022-10-17T17:05:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc3 -->
      </class> <!-- basicsOfTestNG.firstTestNGProgram -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
